import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import React, { useState, useRef } from 'react'
import { Input } from '@chakra-ui/react'
import { Button } from '@chakra-ui/react'

const Home: NextPage = () => {

  const [text, setText] = useState('');
  const router = useRouter();


  const onFormSubmit = (e: React.SyntheticEvent) => {
    e.preventDefault();
      
      router.push({
        pathname: '/user/' + text + '/overview',
      })
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Draft Sniper</title>
        <meta name="An app for sniping those picks" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <div className="App">
            <header className="App-header">
                <h1>Draft Sniper</h1>
            </header>

            <form onSubmit={onFormSubmit}>
                <Input placeholder="LeagueID or Username" value={text} onChange={(e) => setText(e.target.value)} />
                <Button type="submit" colorScheme="blue">Submit</Button>
            </form>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
